### ISSUE TITLE
Non-Parkour players effected

### ISSUE THREAD

**Issue by coralpapa** [AerWyn81/AParkour#10]
just updated to this version from the original. 
Seems to be stopping players from doing anything(place blocks, open chest, ect) even if they aren't in a parkour.

**Comment by coralpapa** [comment]
just heads up i looked at the code and it was Event_Click.java

    @EventHandler
    public void onClicker(PlayerInteractEvent e) {
        if (e.getAction() != Action.RIGHT_CLICK_AIR && e.getAction() != Action.RIGHT_CLICK_BLOCK)
            return;

        e.setCancelled(true);

        ItemStack itemOnHand;
        Player p = e.getPlayer();

**Comment by AerWyn81** [comment]
Hey, u're right. I pushed a fix, thanks!

**Comment by coralpapa** [comment]
No prob, thanks for keeping this plugin alive and up to date
