### ISSUE TITLE
Potion Effects Don't clear

### ISSUE THREAD

**Issue by coralpapa** [AerWyn81/AParkour#12]
Seems Potion Effects are being stored to the player's Profile but isn't being cleared allowing them to keep effects like speed, ect.

https://github.com/AerWyn81/AParkour/blob/3b02040683755cd85383a310109bda4fe02fa2ac/src/main/java/me/davidml16/aparkour/handlers/PlayerDataHandler.java#L95

**Comment by AerWyn81** [comment]
Hi thanks for reporting this issue. Should be fixed in the version [3.7.9](https://github.com/AerWyn81/AParkour/releases/tag/3.7.9)

**Comment by coralpapa** [comment]
Awesome, thanks for the fast response
