### ISSUE TITLE
PlaceholderAPI integration issues

### ISSUE THREAD

**Issue by aljaxus** [AerWyn81/AParkour#2]
*Opening the issue here as this repo is more active than the original one*

---

Getting the following error:

```
[02:38:52 WARN]: [LeaderHeadsRevamped] Could not fetch placeholder %aparkour_bt_lobby% from plugin PlaceholderAPI. Is the plugin properly installed?
[02:38:52 WARN]: java.lang.NoSuchMethodError: 'java.util.HashMap me.davidml16.aparkour.api.ParkourAPI.getParkours()'
[02:38:52 WARN]:        at me.davidml16.aparkourexpansion.Placeholders.onRequest(Placeholders.java:54)
[02:38:52 WARN]:        at PlaceholderAPI-2.10.10.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:160)
[02:38:52 WARN]:        at PlaceholderAPI-2.10.10.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70)
[02:38:52 WARN]:        at LeaderHeads-4.0.6.jar//tech.panoply.leaderheads.c.a.e.a(e.java:3)
[02:38:52 WARN]:        at LeaderHeads-4.0.6.jar//tech.panoply.leaderheads.d.e.a(e.java:13)
[02:38:52 WARN]:        at LeaderHeads-4.0.6.jar//tech.panoply.leaderheads.e.e.a(e.java:185)
[02:38:52 WARN]:        at LeaderHeads-4.0.6.jar//tech.panoply.leaderheads.f.b.a(b.java:29)
[02:38:52 WARN]:        at LeaderHeads-4.0.6.jar//tech.panoply.leaderheads.e.e.a(e.java:113)
[02:38:52 WARN]:        at LeaderHeads-4.0.6.jar//tech.panoply.leaderheads.e.e.c(e.java:224)
[02:38:52 WARN]:        at LeaderHeads-4.0.6.jar//tech.panoply.leaderheads.e.f.run(f.java:1)
[02:38:52 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[02:38:52 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[02:38:52 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[02:38:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[02:38:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[02:38:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

This is when I try to use the placeholders. Leaderheads is just trying to get the placeholder value.
The root cause is the [PAPI expansion](https://api.extendedclip.com/expansions/aparkour/). It does not even have the repository available anymore.

I'd like to ask you if you would be so kind to develop a new expansion jar that actually works.

**Comment by AerWyn81** [comment]
Hi, no worries, I can maintain the plugin as best I can while the developer takes it back or on my free time. 

For your issue, I cannot reproduce it so I'll need more details.

Here is what I did:

- Setup a 1.17.1 server under Airplane, plugins:
  - AParkour 3.6.0
  - HolographicDisplay 2.4.8
  - LeaderHeads 4.0.6
  - PlaceholderAPI 2.10.10
- Create a parkour and I setup LeaderHeads : 
![Image](https://i.imgur.com/swWHRRR.png)

I had no error, and the placeholder is reporting the information correctly

**Comment by aljaxus** [comment]
Mkay - I just tested it again, same versions as you (except HD being 2.4.9) and I'm still getting the same error.
Are you using something else than the `aparkour` addon for PAPI?

I tried full-clean "reinstall" (eg. rename folder, setup everything again) and yet the same error is throw.
I've also tested with airplane#89 and same result. Can you send me a backup of your test server so I can try it out. Maybe it is some OS-specific issue though it seems very unlikely I'd like to test any scenario I can think of.

Feel free to upload it here; https://cloud.aljaxus.eu/index.php/s/qAoEbDn4TRjF8kt

**Comment by AerWyn81** [comment]
> Are you using something else than the aparkour addon for PAPI?

I didn't need to use this to get the placeholder. It's related to the command `/papi ecloud download AParkour` ?

**Comment by aljaxus** [comment]
> I didn't need to use this to get the placeholder

How did you get the placeholder if not via the PAPI extension?

> It's related to the command /papi ecloud download AParkour ?

Yes - that command downloads the aparkour extension for PAPI.

**Comment by aljaxus** [comment]
ref; https://api.extendedclip.com/expansions/aparkour/

De-compiled the jar because source is unavailable.

```java
package me.davidml16.aparkourexpansion;

import me.clip.placeholderapi.expansion.PlaceholderExpansion;
import me.davidml16.aparkour.api.ParkourAPI;
import me.davidml16.aparkour.data.Parkour;
import org.bukkit.Bukkit;
import org.bukkit.OfflinePlayer;

public class Placeholders extends PlaceholderExpansion {
  public boolean canRegister() {
    return (Bukkit.getPluginManager().getPlugin("AParkour") != null);
  }
  
  public boolean register() {
    if (!canRegister())
      return false; 
    return super.register();
  }
  
  public String getIdentifier() {
    return "aparkour";
  }
  
  public String getAuthor() {
    return "DavidML16";
  }
  
  public String getVersion() {
    return "1.0.0";
  }
  
  public String onRequest(OfflinePlayer player, String identifier) {
    if (player == null)
      return ""; 
    ParkourAPI api = new ParkourAPI();
    if (identifier.equals("ct"))
      return "" + api.getCurrentTime(player.getPlayer()); 
    if (identifier.equals("ctf"))
      return "" + api.getCurrentTimeFormatted(player.getPlayer()); 
    for (Parkour parkour : api.getParkours().values()) {
      if (identifier.equals("lt_" + parkour.getId())) {
        int time = api.getLastTime(player.getPlayer(), parkour.getId());
        if (time == 0)
          return "N/A"; 
        return "" + time;
      } 
      if (identifier.equals("ltf_" + parkour.getId())) {
        int time = api.getLastTime(player.getPlayer(), parkour.getId());
        if (time == 0)
          return "N/A"; 
        return "" + api.getLastTimeFormatted(player.getPlayer(), parkour.getId());
      } 
      if (identifier.equals("bt_" + parkour.getId())) {
        int time = api.getBestTime(player.getPlayer(), parkour.getId());
        if (time == 0)
          return "N/A"; 
        return "" + time;
      } 
      if (identifier.equals("btf_" + parkour.getId())) {
        int time = api.getBestTime(player.getPlayer(), parkour.getId());
        if (time == 0)
          return "N/A"; 
        return "" + api.getBestTimeFormatted(player.getPlayer(), parkour.getId());
      } 
    } 
    return null;
  }
}
```


Line 54 is the issue;

```java
for (Parkour parkour : api.getParkours().values()) {
```

**Comment by AerWyn81** [comment]
Whut ? You don't need to have this plugin to retrieve placeholders. This code is already in the plugin. Did you try without the expansion ?

**Comment by aljaxus** [comment]
> Did you try without the expansion ?

Just did;
![image](https://user-images.githubusercontent.com/24414483/134562761-eb47e750-91d5-49ac-bd2e-4734f914e484.png)

Does AParkour hook onto Leaderheads or PAPI because I don't see any other way that it would work :<

**Comment by aljaxus** [comment]
To answer my question; yes it does hook into PAPI. But for some reasons placeholders aren't registred.
https://github.com/AerWyn81/AParkour/blob/master/src/main/java/me/davidml16/aparkour/placeholders/PlaceholderHook.java

**Comment by AerWyn81** [comment]
Did u see that line ` [PlaceholderAPI] Successfully registered expansion: aparkour` in logs at server startup ?

**Comment by aljaxus** [comment]
Yes - it now works. I assumed that I needed the aparkour expansion installed for PAPI which breaks the functionality.

**Comment by aljaxus** [comment]
reported the issue in HelpChat discord; [message link](https://discord.com/channels/164280494874165248/573429521554866178/890676221803900998)
