### ISSUE TITLE
Flying not detected

### ISSUE THREAD

**Issue by aljaxus** [AerWyn81/AParkour#3]
As title says, player flying is not detected while parkouring.

* Using the [Simple Fly Plugin](https://www.spigotmc.org/resources/simple-fly-plugin.38565/).
* Option in AParkour config is enabled.
* No exceptions are thrown on startup or when I start flying.
* I do not know why it's not detecting flying.

**Comment by AerWyn81** [comment]
Fixed in [#58486fd](https://github.com/AerWyn81/AParkour/commit/58486fdb379d94af8347d699a5bab7eef0a8fdc0).
