### ISSUE TITLE
New items/blocks can't be handled in the "walkable blocks"

### ISSUE THREAD

**Issue by aljaxus** [AerWyn81/AParkour#4]
### THE ISSUE

In [the "flattering" MC update](https://minecraft.fandom.com/wiki/Java_Edition_1.13/Flattening) numerical block IDs were fully removed.

This represents an unhandled issue in AParkor when using the "walkable blocks" functionality because the plugin uses numerical block IDs to store the data in the parkour save file.

The main source file in question is the [WalkableBlock.java](https://github.com/AerWyn81/AParkour/blob/b595cb4c1df2fb62eaab133fcb1a80ea005e5b9d/src/main/java/me/davidml16/aparkour/data/WalkableBlock.java).

### REPLICATE IT

1. Create an 1.17.1 server
2. install AParkour
3. Create a new parkour
  3.1. Try to add `BARREL` block to "walkable blocks" list of items via the GUI `/aparkour setup PARKOUR`.
  3.2. Nothing will happen (compared to other "old" blocks which can still be accessed via a numeric ID)
4. Stop the server
  4.1. Edit the newly created parkour savefile
  4.2. add the `BARREL` block ID to the "walkableBlocks" array
5. start the server
6. watch the plugin throw the exception on load because it doesn't have a clue what that block is

### SOLUTION

Replace the use of numerical IDs with newer block/item [naming system](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html).

**Comment by AerWyn81** [comment]
This task might be a little more complicated/long. I'm thinking of developing it, but it will take a little more time

**Comment by AerWyn81** [comment]
Commit [#3b02040](https://github.com/AerWyn81/AParkour/commit/3b02040683755cd85383a310109bda4fe02fa2ac) is the first brick, not necessarily the most optimized, but functional and to meet the need now
