### ISSUE TITLE
AutoRestart config option should have a better description

### ISSUE THREAD

**Issue by aljaxus** [AerWyn81/AParkour#7]
I have no clue what `AutoRestart` does. A quick glance at the codebase suggests that it's related to restarting the "parkouring attempt" (session if you will) but an average user might assume that it's related to restarting the server.

So yeah... More info in the config comment, please ?

**Comment by AerWyn81** [comment]
Yes you were right, this is for restart the Parkour session quickly. I changed the name of the configuration to `FastRestart` and improved the description in the config
