### ISSUE TITLE
Make "restart attempt" confirmation menu optional.

### ISSUE THREAD

**Issue by aljaxus** [AerWyn81/AParkour#8]
As title says; add a config option to enable/disable the confirmation menu.

* if disabled, reset/restart item will directly restart the attempt
* if enable, open the confirmation menu (current behaviour)

**Comment by AerWyn81** [comment]
Added in [#9c30403](https://github.com/AerWyn81/AParkour/commit/9c30403a014383da38424622dbee5f54264872c8).
